spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework: # 추가!
        security: debug # 추가!
auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168
